const $ = (id) => document.getElementById(id)
const labels = { queued:'Queued', running:'Gathering', waiting_tool:'Waiting on tool', waiting_user:'Waiting for you', blocked:'Blocked', retrying:'Trying again', done:'Finished', failed:'Failed', canceled:'Canceled', stale:'Quiet too long' }
const icons = { queued:'○', running:'🐝', waiting_tool:'🛠️', waiting_user:'👋', blocked:'⚠️', retrying:'↻', done:'🍯', failed:'✕', canceled:'−', stale:'…' }
let currentRun = null, selectedId = null, privacy = true
function age(iso){ if(!iso) return '—'; const s=Math.max(0,Math.round((Date.now()-new Date(iso))/1000)); if(s<60)return `${s}s ago`; const m=Math.round(s/60); return m<60?`${m}m ago`:`${Math.round(m/60)}h ago` }
function duration(start,end){ if(!start) return '—'; const ms=Math.max(0,new Date(end||Date.now())-new Date(start)); const s=Math.round(ms/1000); if(s<60)return `${s}s`; const m=Math.floor(s/60), r=s%60; if(m<60)return r?`${m}m ${r}s`:`${m}m`; const h=Math.floor(m/60); return `${h}h ${m%60}m` }
function scoutEvents(scout){ return (currentRun?.events||[]).filter(e=>e.scoutId===scout?.id).slice(-5).reverse() }
async function loadRun(){ try{ const reg=await fetch('../runs/registry.json',{cache:'no-store'}).then(r=>r.json()); const entry=reg.runs?.[0]; if(!entry) throw new Error('empty registry'); currentRun=await fetch(`../${entry.path}`,{cache:'no-store'}).then(r=>r.json()) }catch{ currentRun=window.APIARY_SAMPLE_RUN } privacy = currentRun.privacyMode !== false; render() }
function statusClass(s){ return ['waiting_tool','waiting_user'].includes(s)?s:s||'queued' }
function render(){ const run=currentRun; if(!run) return; const sum=run.summary||{}; $('countRunning').textContent=sum.running||0; $('countWaiting').textContent=sum.waiting||0; $('countBlocked').textContent=sum.blocked||0; $('countDone').textContent=sum.done||0; $('runTitle').textContent=run.title; $('runMeta').textContent=`${labels[run.status]||run.status} · updated ${age(run.updatedAt)}`; $('privacyToggle').textContent=`Privacy: ${privacy?'on':'off'}`; $('decision').classList.toggle('hidden',!run.decisionAwaiting); $('decision').textContent=run.decisionAwaiting?`Waiting for you: ${run.decisionAwaiting}`:''; renderHive(run.scouts||[]); renderEvents(run.events||[]); renderDetails((run.scouts||[]).find(s=>s.id===selectedId)) ; $('lastRefresh').textContent=`Refreshed ${new Date().toLocaleTimeString()}` }
function renderHive(scouts){ $('hive').innerHTML=''; for(const scout of scouts){ const btn=document.createElement('button'); btn.className=`cell ${statusClass(scout.status)}`; btn.type='button'; btn.innerHTML=`<span class="hex"></span><span class="cell-content"><span class="bee">${icons[scout.status]||'✦'}</span><strong>${scout.label}</strong><small>${labels[scout.status]||scout.status} · ${scout.progress||0}%</small></span>`; btn.onclick=()=>{selectedId=scout.id; renderDetails(scout)}; $('hive').appendChild(btn) } }
function renderDetails(scout){ if(!scout){ $('detailTitle').textContent='Pick a cell'; $('detailStatus').textContent='No scout selected'; $('detailRole').textContent='—'; $('detailModel').textContent='—'; $('detailSeen').textContent='—'; $('detailElapsed').textContent='—'; $('detailSummary').textContent='Select a scout cell to inspect status, model, elapsed time, and recent events.'; $('detailAwaiting').textContent='—'; $('detailEvents').innerHTML=''; $('detailEventCount').textContent='0 events'; return } $('detailTitle').textContent=scout.label; $('detailStatus').textContent=labels[scout.status]||scout.status; $('detailRole').textContent=scout.role; $('detailModel').textContent=`${scout.modelRole||'default'} → ${scout.model||'host-default'}`; $('detailSeen').textContent=age(scout.lastSeenAt); $('detailElapsed').textContent=duration(scout.startedAt, scout.completedAt); $('detailSummary').textContent=privacy && !selectedId ? 'Privacy mode hides details until selected.' : (scout.summary||'No summary yet.'); $('detailAwaiting').textContent=scout.awaiting||'—'; const ev=scoutEvents(scout); $('detailEventCount').textContent=`${ev.length} event${ev.length===1?'':'s'}`; $('detailEvents').innerHTML=''; for(const evt of ev){ const li=document.createElement('li'); li.innerHTML=`<strong>${evt.severity||'info'}</strong> · ${age(evt.ts)} · ${evt.message}`; $('detailEvents').appendChild(li) } }
function renderEvents(events){ $('events').innerHTML=''; for(const evt of events.slice(-6).reverse()){ const li=document.createElement('li'); li.innerHTML=`<strong>${evt.severity||'info'}</strong> · ${age(evt.ts)} · ${evt.message}`; $('events').appendChild(li) } }
$('refreshBtn').onclick=loadRun; $('privacyToggle').onclick=()=>{ privacy=!privacy; render() }; $('motionToggle').onclick=()=>document.body.classList.toggle('focus-mode'); document.addEventListener('visibilitychange',()=>{ if(!document.hidden) loadRun() }); loadRun(); setInterval(()=>{ if(!document.hidden) loadRun() },3000)

function hideHelp(){ $('helpBubble').classList.add('hidden'); $('helpBubble').textContent='' }
function showHelp(text){ const bubble=$('helpBubble'); bubble.textContent=text; bubble.classList.remove('hidden'); clearTimeout(window.__helpTimer); window.__helpTimer=setTimeout(hideHelp,5500) }
document.addEventListener('click',(event)=>{ const trigger=event.target.closest('[data-tip]'); if(trigger){ event.preventDefault(); event.stopPropagation(); showHelp(trigger.dataset.tip) } else if(!event.target.closest('#helpBubble')) hideHelp() })
document.addEventListener('keydown',(event)=>{ if(event.key==='Escape') hideHelp() })
